displayName: Traefik Umami Feeder Custom

import: github.com/docloulou/traefik-umami-feeder-custom
type: middleware

summary: A Traefik plugin that feeds Umami Analytics with pageview events
iconPath: .assets/icon.png

testData:
  umamiHost: ""
  umamiToken: ""
  umamiUsername: ""
  umamiPassword: ""
  umamiTeamId: ""
  websites:
    domain: websiteId
  createNewWebsites: false
  distinctIdCookie: ""
